#!perl
use strict;
use warnings;
use Getopt::Long;

GetOptions
	'h|help' => \my $help;

my ($n) = shift =~ /^(\d+)$/;
if ($help || !$n) {
	die usage();
}

use FizzBuzz;

for my $i (1 .. $n) {
	print "$i ", FizzBuzz::fizzbuzz($i);
	print "\n";
}


sub usage {
	return '
Usage: fizzbuzz [OPTIONS] [Number]

  fizzbuzz 100

Options:
  -h, --help      show this message
'

}

