#!perl
use strict;
use warnings;
use Getopt::Long;

GetOptions
	'h|help' => \my $help;

my ($n) = shift =~ /^(\d+)$/;
if ($help || !$n) {
	die usage();
}

use FizzBuzz;

my $output = '';
for my $i (1 .. $n) {
	$output .= "$i " . FizzBuzz::fizzbuzz($i) . "\n";
}

print $output;

sub usage {
	return '
Usage: fizzbuzz [OPTIONS] [Number]

  fizzbuzz 100

Options:
  -h, --help      show this message
'

}

